---
- name: Install Brave Browser
  hosts: all
  become: true

  tasks:
   - name: Install curl
     apt:
        name: curl
        state: latest
        
   - name: Install Keys
     command: "curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
     
     
   - name: Add Brave Browser repository
     shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

   - name: Update apt cache
     apt:
        update_cache: yes
        force_apt_get: yes 
        cache_valid_time: 3600

   - name: Install Brave Browser package
     apt:
        name: brave-browser
        state: present

