---

- hosts: all
  remote_user: m
  become: yes
  become_method: sudo
  tasks:
    - name: "Install Brave Browser"
      apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true        
